.zeropage
.include "zeropage.asm"
.include "concerto_synth/synth_zeropage.asm"

.include "library/preamble.asm"
.include "library/x16.inc"
.include "library/keyboard.inc"
.include "library/screencodes.inc"
.include "library/macros.inc"
.include "concerto_synth/concerto_synth.asm"
.include "debug.asm"
.include "math.asm"
.include "files.asm"
.include "graphics.asm"
.include "sound.asm"
.include "ui.asm"
.include "tracker.asm"




.include "variables.inc"



.include "setup.asm"
