;pattern_using_tracker_notes:
pattern:
.byte   $42, $20      ; row 0
.byte   $45, $25      ; row 1
.byte   $49, $2A      ; row 2
.byte   $52, $35
.byte   $42, $3F
.byte   $FF, $05
.byte   $FF, $3F
.byte   $FF, $05
.byte   $FF, $3F
.byte   $FF, $05
.byte   $FF, $3F
.byte   $52, $FF
.byte   $49, $FF
.byte   $FE, $FF
.byte   $42, $FF
.byte   $FD, $FF    ; row 16
.byte   $42, $FF
.byte   $45, $FF
.byte   $49, $FF
.byte   $52, $FF
.byte   $42, $FF
.byte   $FF, $FF
.byte   $49, $FF
.byte   $FF, $FF
.byte   $52, $FF
.byte   $49, $FF
.byte   $45, $FF
.byte   $52, $FF
.byte   $49, $FF
.byte   $FE, $FF
.byte   $42, $FF
.byte   $FD, $FF      ; row 32
.byte   $42, $20
.byte   $45, $25
.byte   $49, $2A
.byte   $52, $35
.byte   $42, $3A
.byte   $FF, $40
.byte   $49, $3A
.byte   $FF, $39
.byte   $52, $10
.byte   $49, $FF
.byte   $45, $FF
.byte   $52, $FF
.byte   $49, $FF
.byte   $FE, $FF
.byte   $42, $FF
.byte   $FD, $FF
.byte   $42, $FF    ; row 48
.byte   $45, $FF
.byte   $49, $FF
.byte   $52, $FF
.byte   $42, $FF
.byte   $FF, $FF
.byte   $49, $FF
.byte   $FF, $FF
.byte   $52, $FF
.byte   $49, $FF
.byte   $45, $FF
.byte   $52, $FF
.byte   $49, $FF
.byte   $FE, $FF
.byte   $42, $FF
.byte   $45, $FF  ; row 63
